config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"

  devise_for :users, :controllers => {:sessions => "my_devise/sessions"}
  root "static_pages#home"
  get "/static_pages/:page" => "static_pages#show", as: "static_pages"
  resources :places do
    collection {post :search, to: "places#index"}
    resources :reviews, except: :index
  end
  resources :tours do
    collection {post :search, to: "tours#index"}
    resources :bookings, except: [:edit, :update, :index]
  end
  resources :bookings, except: [:edit, :destroy] do
    resources :payments, only: [:new, :create, :update]
  end
  resources :reviews do
    resources :comments
  end
  resources :comments do
    resources :comments
  end
  resources :users
  resources :discounts, only: [:show, :index]
  resources :categories, only: :show
  resources :payments, only: [:show, :index]

  namespace :admin do
    root "static_pages#home", as: "static_pages"
    get "static_pages/:page" => "static_pages#show"
    resources :categories, except: [:show]
    resources :tours do
      collection {post :search, to: "tours#index"}
    end
    resources :bookings, except: [:new, :create] do
      collection {post :search, to: "bookings#index"}
    end
    resources :places, except: [:show] do
      collection {post :search, to: "places#index"}
      resources :reviews, only: [:show, :destroy]
    end
    resources :reviews, only: [:show, :index, :destroy] do
      resources :comments, only: [:show, :destroy]
    end
    resources :users do
      collection {post :search, to: "users#index"}
    end
    resources :discounts do
      collection {post :search, to: "discounts#index"}
    end
    resources :payments,  only: [:show, :index]
    resources :notifications, only: :index
  end
end

app/controllers/admin/static_pages_controller.rb
class Admin::StaticPagesController < ApplicationController
  def show
    if valid_page?
      render "admin/static_pages/#{params[:page]}"
    else
      render file: "public/404.html", status: :not_found
    end
  end

  private
  def valid_page?
    File.exist? Pathname
      .new Rails.root + "app/views/static_pages/#{params[:page]}.html.erb"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :set_search, :get_random

  def show
    if valid_page?
      render "static_pages/#{params[:page]}"
    else
      render file: "public/404.html", status: :not_found
    end
  end

  private
  def valid_page?
    File.exist? Pathname
      .new Rails.root + "app/views/static_pages/#{params[:page]}.html.erb"
  end

  def set_search
    @search = Tour.search params[:q]
  end

  def get_random
    @places = Place.order("RAND()").limit(5)
    @discounts = Discount.order("RAND()").limit(5)
  end
end

app/views/static_pages/_home_page.html.erb
<link href="css/bootstrap.css" rel="stylesheet" type="text/css" media="all">
<script src="js/jquery-1.11.0.min.js"></script>
<link href="css/style.css" rel="stylesheet" type="text/css" media="all"/>
<link href="css/style1.css" rel="stylesheet" type="text/css" media="all" />

<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!--Google Fonts-->
<link href='//fonts.googleapis.com/css?family=Hind:400,300' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Aladin' rel='stylesheet' type='text/css'>
<!--google fonts-->
<!-- animated-css -->
<!-- <link href="css/animate1.css" rel="stylesheet" type="text/css" media="all"> -->
<script src="js/wow.min.js"></script>
<script>
  new WOW().init();
</script>
<!-- animated-css -->
<script src="js/modernizr.js"></script>
<script>
  $(document).ready(function(){
    if (Modernizr.touch) {
      // show the close overlay button
      $(".close-overlay").removeClass("hidden");
      // handle the adding of hover class when clicked
      $(".branch-gd").click(function(e){
        if (!$(this).hasClass("hover")) {
          $(this).addClass("hover");
        }
      });
      // handle the closing of the overlay
      $(".close-overlay").click(function(e){
        e.preventDefault();
        e.stopPropagation();
        if ($(this).closest(".branch-gd").hasClass("hover")) {
          $(this).closest(".branch-gd").removeClass("hover");
        }
      });
  } else {
    // handle the mouseenter functionality
    $(".branch-gd").mouseenter(function(){
      $(this).addClass("hover");
    })
    // handle the mouseleave functionality
    .mouseleave(function(){
      $(this).removeClass("hover");
      });
    }
  });
</script>
<script src="js/bootstrap.min.js"></script>

<!--header start here-->
  <!-- NAVBAR
    ================================================== -->
<div class="header">
  <div class="fixed-header">
    <div class="navbar-wrapper">
      <div class="container">
        <nav class="navbar navbar-inverse navbar-static-top">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <div class="logo wow slideInLeft" data-wow-delay="0.3s">
              <%= link_to root_path do %>
                <%= image_tag "logo.png", alt: "logo", style: "margin-left:20px;" %>
              <% end %>
            </div>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <nav class="cl-effect-16" id="cl-effect-16">
              <ul class="nav navbar-nav">
                <li><%= link_to t("header.home"), root_path, class: "active" %></li>
                <li class="has-child">
                  <%= link_to t("header.categories"), root_path %>
                  <ul class="child">
                    <% @categories.each do |category| %>
                      <li>
                        <%= link_to category.title, category %>
                      </li>
                    <% end %>
                  </ul>
                </li>
                <li><%= link_to t("home.top_tours"), tours_path %></li>
                <li><%= link_to t("header.destinations"), places_path %></li>
                <li><%= link_to t("header.discounts"), discounts_path %></li>
                <li><%= link_to t("header.contact_us"), static_pages_path(:contact) %></li>
                <% if user_signed_in? %>
                  <li class="has-child">
                    <%= link_to current_user.username, current_user %>
                    <ul class="child">
                      <li><%= link_to t("header.profile"), current_user %></li>
                      <li>
                        <%= link_to t("edit"), edit_user_registration_path %>
                      </li>
                      <li>
                        <%= link_to t("header.logout"),
                          destroy_user_session_path, method: :delete %>
                      </li>
                    </ul>
                  </li>
                <% else %>
                  <li class="lt-child">
                    <%= link_to new_user_session_path do %>
                      <i class="fa fa-sign-in" aria-hidden="true"></i><%= t "header.login" %>
                    <% end %>
                  </li>
                <% end %>
              </ul>
            </nav>
          </div>
          <div class="clearfix"> </div>
        </nav>
      </div>
      <div class="clearfix"> </div>
    </div>
   </div>
</div>
<!--header end here-->
<!--banner  start hwew-->
<div class="banner">
  <div class="container">
    <div class="banner-main wow zoomIn" data-wow-delay="0.3s">
      <h2>MY TOURS</h2>
      <h6>We Make Awesome Tours</h6>
      <p><%= t "company.intro" %></p>
    </div>
  </div>
</div>
<!--BANNER END HERE-->
<!--information start here-->
<div class="information">
  <div class="container">
    <div class="information-main">
      <div class="information-grid five-star wow slideInLeft" data-wow-delay="0.3s">
        <div class="col-md-4 hotel-info">
          <div class="info-right">
            <h4>Thể loại</h4>
            <p><%= t "company.phongphu" %></p>
          </div>
          <div class="clearfix"> </div>
        </div>
        <div class="col-md-4 hotel-info">
          <div class="info-right">
            <h4>Dịch vụ</h4>
            <p><%= t "company.services" %></p>
          </div>
          <div class="clearfix"> </div>
        </div>
        <div class="col-md-4 hotel-info">
          <div class="info-right">
            <h4>An toàn</h4>
            <p><%= t "company.secure" %></p>
          </div>
          <div class="clearfix"> </div>
        </div>
        <div class="clearfix"> </div>
      </div>
      <div class="information-grid wow slideInRight" data-wow-delay="0.3s">
        <div class="col-md-4 hotel-info">
          <div class="info-right">
            <h4>Giá cả</h4>
            <p><%= t "company.price" %></p>
          </div>
          <div class="clearfix"> </div>
        </div>
        <div class="col-md-4 hotel-info">
          <div class="info-right">
            <h4>Khách sạn</h4>
            <p><%= t "company.hotel" %></p>
          </div>
          <div class="clearfix"> </div>
        </div>
        <div class="col-md-4 hotel-info">
          <div class="info-right">
            <h4>Lữ hành</h4>
            <p><%= t "company.travel" %></p>
          </div>
          <div class="clearfix"> </div>
        </div>
        <div class="clearfix"> </div>
      </div>
      <div class="clearfix"> </div>
    </div>
  </div>
</div>
<!--information end here-->
<!--leaves start here-->
<div class="leaves">
  <div class="container">
    <div class="leaves-main wow zoomIn" data-wow-delay="0.3s">
      <h1>Find Your Tour Today</h1>
      <h6>Chăm sóc khách hàng 24/7</h6>
      <p>Còn chần chừ gì mà không đặt ngay tour</p>
      <%= link_to t("home.tour"), tours_path %>
    </div>
  </div>
</div>
<!--leaves end here-->
<!--branches start here-->
<div class="home-block">
  <div class="container">
    <div class="home-main">
      <div class="home-top">
        <h3>Chương trình khuyến mại đang diễn ra</h3>
      </div>
      <div  id="effect-5" class="branch-btm">
        <div class="col-md-12">
          <% @discounts.each do |discount| %>
            <div class="col-md-4">
              <%= image_tag "london.jpg", alt: "discount", class: "img-responsive" %>
              <%= link_to discount.name, discount_path(discount)  %>
              </div>
            <% end %>
        </div>
      </div>
      <div class="clearfix"> </div>
    </div>
  </div>
</div>
<!--branches end here-->

<!--homegrids start here-->
<div class="home-block">
  <div class="container">
    <div class="home-main">
      <div class="home-top">
        <h3>Tour du lịch mới nhất</h3>
      </div>
      <div  id="effect-5" class="branch-btm">
        <div class="col-md-12">
          <% @tours.each do |tour| %>
            <div class="col-md-4">
              <%= image_tag "london.jpg", alt: "discount", class: "img-responsive" %>
              <%= link_to tour.name, tour  %>
              </div>
            <% end %>
        </div>
      </div>
      <div class="clearfix"> </div>
    </div>
  </div>
</div>
<!--home grid end here-->
<!--footer start here-->
<div class="footer">
  <div class="container">
    <div class="footer-main">
      <div class="col-md-3 ftr-grid wow zoomIn" data-wow-delay="0.3s">
        <div class="ftr-logo">
          <%= image_tag "logo.png", alt: "" %>
        </div>
        <p>Sứ mệnh của chúng tôi là sự hài lòng của du khách</p>
      </div>
      <div class="col-md-3 ftr-grid ftr-mid wow zoomIn" data-wow-delay="0.3s">
         <h3><%= t "company.address" %></h3>
         <span class="ftr-line flm"> </span>
        <strong><%= t "company.name" %></strong>
        <p><%= t "company.stress" %></p>
        <p><%= t "company.city" %></p>
        <p><%= t "company.hotline" %></p>
        <p><%= t "company.email" %></p>
      </div>
      <div class="col-md-3 ftr-grid ftr-rit wow zoomIn" data-wow-delay="0.3s">
         <h3><%= t "header.contact_us" %></h3>
         <form>
          <input type="text" value="Email" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Email';}">
          <input type="submit" value="Send" />
         </form>
      </div>
      <div class="col-md-3 ftr-grid ftr-last-gd ftr-rit wow zoomIn" data-wow-delay="0.3s">
         <h3>Quick Link</h3>
        <ul class="ftr-nav">
          <li><%= link_to t("header.home"), root_path, class: "active" %></li>
          <li><%= link_to t("header.categories"), root_path %></li>
          <li><%= link_to t("home.top_tours"), tours_path %></li>
          <li><%= link_to t("header.destinations"), places_path %></li>
          <li><%= link_to t("header.discounts"), discounts_path %></li>
          <li><%= link_to t("header.contact_us"), static_pages_path(:contact) %></li>
       </ul>
      </div>
      <div class="clearfix"> </div>
    </div>
  </div>
</div>
<!--footer end here-->
<!--copy rights start here-->
<div class="copy-right">
  <div class="container">
    <div class="copy-rights-main wow zoomIn" data-wow-delay="0.3s">
      <p>© 2016 My Tour. All Rights Reserved | Design by TourMaker </p>
    </div>
  </div>
</div>

app/views/static_pages/contact.html.erb
<% provide :title, t(".title") %>

<div class="container">
  <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="well well-sm" style="margin-top:50px;">
          <form class="form-horizontal" action="" method="post">
          <fieldset>
            <legend class="text-center"><%= t "static_pages.contact.contact_title" %></legend>

            <!-- Name input-->
            <div class="form-group">
              <label class="col-md-3 control-label" for="name"><%= t ".name" %>
              </label>
              <div class="col-md-9">
                <input id="name" name="name" type="text" placeholder="Vui lòng nhập họ tên..."
                  class="form-control">
              </div>
            </div>

            <!-- Email input-->
            <div class="form-group">
              <label class="col-md-3 control-label" for="email">
                <%= t ".email" %>
              </label>
              <div class="col-md-9">
                <input id="email" name="email" type="text"
                  placeholder="Vui lòng nhập email..." class="form-control">
              </div>
            </div>

            <!-- Message body -->
            <div class="form-group">
              <label class="col-md-3 control-label" for="message">
                <%= t ".message" %>
              </label>
              <div class="col-md-9">
                <textarea class="form-control" id="message" name="message"
                  placeholder="Vui lòng để lại tin nhắn tại đây..."
                  rows="5"></textarea>
              </div>
            </div>

            <!-- Form actions -->
            <div class="form-group">
              <div class="col-md-12 text-center">
                <button type="submit" class="btn btn-primary btn-lg">
                  <%= t ".submit" %>
                </button>
              </div>
            </div>
          </fieldset>
          </form>
        </div>
      </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<% provide :title, t(".title") %>

<%= search_form_for @search, url: search_tours_path, method: :post  do |f| %>
  <div class="field">
    <%= f.label :name_cont, t("name_cont") %>
    <%= f.text_field :name_cont %>
  </div>
  <div class="action"><%= f.submit t "search" %></div>
<% end %>