config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"

  devise_for :users, :controllers => {:sessions => "my_devise/sessions"}
  root "static_pages#home"
  get "/static_pages/:page" => "static_pages#show", as: "static_pages"
  resources :places do
    collection {post :search, to: "places#index"}
    resources :reviews, except: :index
  end
  resources :tours do
    collection {post :search, to: "tours#index"}
    resources :bookings, except: [:edit, :update, :index]
  end
  resources :bookings, except: [:edit, :destroy] do
    resources :payments, only: [:new, :create, :update]
  end
  resources :reviews do
    resources :comments
  end
  resources :comments do
    resources :comments
  end
  resources :users
  resources :discounts, only: [:show, :index]
  resources :categories, only: :show
  resources :payments, only: [:show, :index]

  namespace :admin do
    root "static_pages#home", as: "static_pages"
    get "static_pages/:page" => "static_pages#show"
    resources :categories, except: [:show]
    resources :tours do
      collection {post :search, to: "tours#index"}
    end
    resources :bookings, except: [:new, :create] do
      collection {post :search, to: "bookings#index"}
    end
    resources :places, except: [:show] do
      collection {post :search, to: "places#index"}
      resources :reviews, only: [:show, :destroy]
    end
    resources :reviews, only: [:show, :index, :destroy] do
      resources :comments, only: [:show, :destroy]
    end
    resources :users do
      collection {post :search, to: "users#index"}
    end
    resources :discounts do
      collection {post :search, to: "discounts#index"}
    end
    resources :payments,  only: [:show, :index]
    resources :notifications, only: :index
  end
end

app/models/tour.rb
class Tour < ApplicationRecord
  enum :currency => [:vnd, :usd]
  enum :status => [:coming, :ongoing, :expried]

  belongs_to :category
  belongs_to :discount
  belongs_to :start_place, class_name: 'Place', foreign_key: 'start_place_id'
  belongs_to :end_place, class_name: 'Place', foreign_key: 'end_place_id'

  has_many :bookings, dependent: :destroy
  has_many :visitors, through: :bookings

  validates :end_date, presence: true, date: { after: :start_date,
    message: "must after Start date" }
  validates :start_date, presence: true,
    date: { after_or_equal_to: Proc.new { Date.today },
    message: "must be at least #{(Date.today + 1).to_s}" }, on: :create
  validates :start_place_id, presence: true
  validates :end_place_id, presence: true
  validates :category_id, presence: true
end

app/controllers/admin/tours_controller.rb
class Admin::ToursController < ApplicationController
  load_and_authorize_resource

  def index
    @search = Tour.search params[:q]
    @tours = @search.result
    @search.build_condition if @search.conditions.empty?
    @search.build_sort if @search.sorts.empty?
  end

  def show
  end

  def new
    @categories = Category.all
    @discounts = Discount.where.not status: :expried
    @places = Place.all
  end

  def create
    @category = Category.find_by_id params[:category_id]
    @discount = Discount.find_by_id params[:discount_id]
    @place = Place.find_by_id params[:place_id]
    if @tour.save
      flash[:notice] = t "tour.create_success"
      redirect_to admin_tours_path
    else
      flash[:alert] = t "tour.create_fail"
      @categories = Category.all
      render :new
    end
  end

  def edit
    @categories = Category.all
    @discounts = Discount.all
  end

  def update
    @category = Category.find_by_id params[:category_id]
    @discount = Discount.find_by_id params[:discount_id]
    if @tour.update_attributes tour_params
      flash[:notice] = t "tour.update_success"
      redirect_to admin_tours_path
    else
      flash[:alert] = t "tour.update_fail"
      render :edit
    end
  end

  def destroy
    if @tour.destroy
      flash[:notice] = t "tour.delete_success"
      redirect_to admin_tours_path
    else
      flash[:alert] = t "tour.delete_fail"
      redirect_to admin_tours_path
    end
  end

  private
  def tour_params
    params.require(:tour).permit :name, :price, :category_id,
      :currency, :start_date, :end_date, :min_visitors, :max_visitors,
      :accommodation, :meals, :transport, :additional_services,
      :discount_id, :start_place_id, :end_place_id
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  load_and_authorize_resource

  def index
    @search = Tour.search params[:q]
    @tours = @search.result
    @search.build_condition if @search.conditions.empty?
    @search.build_sort if @search.sorts.empty?
  end

  def show
    @visitors = @tour.bookings.collect {|b| b.visitors }
    @left = @tour.max_visitors - @visitors.count
  end
end

app/views/admin/tours/_condition_fields.html.erb
<div class="field">
  <%= f.attribute_fields do |a| %>
    <%= a.attribute_select %>
  <% end %>
  <%= f.predicate_select %>
  <%= f.value_fields do |v| %>
    <%= v.text_field :value %>
  <% end %>
  <%= link_to t("remove"), "#", class: "remove_fields" %>
</div>

app/views/admin/tours/_tour_form.html.erb
<%= form_for [:admin, @tour], html: {class: "form-horizontal form-label-left"} do |f| %>
  <div class="form-group">
    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
      <%= render "shared/error_messages", object: f.object %>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">
      <%= t "admin_tours.name" %> <span class="required">*</span>
    </label>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <%= f.text_field :name, class: "form-control", required: true,
        placeholder: "Vui lòng nhập tên tour du lịch..." %>
    </div>
  </div>

  <div class="form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">
      <%= t "admin_categories.title" %> <span class="required">*</span>
    </label>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <select class="select2_single form-control" tabindex="-1" id="tour_category_id" name="tour[category_id]">
        <option></option>
        <% @categories.each do |category| %>
          <option value="<%= category.id %>"><%= category.title %></option>
        <% end %>
      </select>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">
      <%= t "admin_bookings.discount" %> <span class="required">*</span>
    </label>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <select class="select2_single form-control" tabindex="-1" id="tour_discount_id" name="tour[discount_id]">
        <option></option>
        <% @discounts.each do |discount| %>
          <option value="<%= discount.id %>"><%= discount.name %></option>
        <% end %>
      </select>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">
      <%= t "admin_tours.start_place" %> <span class="required">*</span>
    </label>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <select class="select2_single form-control" tabindex="-1" id="tour_start_place_id" name="tour[start_place_id]">
        <option></option>
        <% @places.each do |place| %>
          <option value="<%= place.id %>"><%= place.name %></option>
        <% end %>
      </select>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">
      <%= t "admin_tours.end_place" %> <span class="required">*</span>
    </label>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <select class="select2_single form-control" tabindex="-1" id="tour_end_place_id" name="tour[end_place_id]">
        <option></option>
        <% @places.each do |place| %>
          <option value="<%= place.id %>"><%= place.name %></option>
        <% end %>
      </select>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">
      <%= t "admin_tours.price" %> <span class="required">*</span>
    </label>
    <div class="col-md-4 col-sm-6 col-xs-12">
      <%= f.text_field :price, class: "form-control", required: true,
        placeholder: "Vui lòng nhập giá tiền..." %>
    </div>
    <div class="col-md-2">
      <select name="tour[currency]", class="form-control">
        <option value="vnd">VNĐ</option>
        <option value="usd">USD</option>
      </select>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">
      <%= t "admin_tours.date" %><span class="required">*</span>
    </label>
    <div class="col-md-3 col-sm-6 col-xs-12">
      <%= f.text_field :start_date, class: "form-control datetimepicker",
        placeholder: "Ngày bắt đầu..." %>
    </div>
    <div class="col-md-3 col-sm-6 col-xs-12">
      <%= f.text_field :end_date, class: "form-control datetimepicker",
        placeholder: "Ngày kết thúc..." %>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">
      <%= t "admin_tours.num" %><span class="required">*</span>
    </label>
    <div class="col-md-3 col-sm-6 col-xs-12">
      <%= f.text_field :min_visitors, class: "form-control",
        required: true, placeholder: "SL tối thiểu" %>
    </div>
    <div class="col-md-3 col-sm-6 col-xs-12">
      <%= f.text_field :max_visitors, class: "form-control",
        required: true, placeholder: "SL tối đa" %>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">
      <%= t "admin_tours.accommodation" %> <span class="required">*</span>
    </label>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <%= f.text_area :accommodation, class: "form-control", required: true,
        placeholder: "Vui lòng nhập thông tin chỗ ở..." %>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">
      <%= t "admin_tours.meals" %> <span class="required">*</span>
    </label>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <%= f.text_area :meals, class: "form-control", required: true,
        placeholder: "Vui lòng nhập thông tin bữa ăn..." %>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">
      <%= t "admin_tours.transport" %> <span class="required">*</span>
    </label>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <%= f.text_area :transport, class: "form-control", required: true,
        placeholder: "Vui lòng nhập thông tin phương tiện đi lại..." %>
    </div>
  </div><div class="form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">
      <%= t "admin_tours.service" %> <span class="required">*</span>
    </label>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <%= f.text_area :additional_services, class: "form-control",
        required: true, placeholder: "Vui lòng nhập thông tin dịch vụ đi kèm..." %>
    </div>
  </div>
  <div class="ln_solid"></div>
  <div class="form-group">
    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
      <%= f.submit t("save"), class: "btn btn-success" %>
    <%= link_to t("cancel"), admin_places_path, class: "btn btn-primary" %>
    </div>
  </div>
<% end %>
<!-- Select2 -->
  <script>
    $(document).ready(function() {
      $(".select2_single").select2({
        placeholder: "Please select ...",
        allowClear: true
      });
      $(".select2_group").select2({});
      $(".select2_multiple").select2({
        maximumSelectionLength: 4,
        placeholder: "With Max Selection limit 4",
        allowClear: true
      });
    });
  </script>
<!-- /Select2 -->

app/views/admin/tours/edit.html.erb
<%= form_for [:admin, @tour], html: {class: "form-horizontal form-label-left"} do |f| %>
  <div class="form-group">
    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
      <%= render "shared/error_messages", object: f.object %>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">
      <%= t "admin_tours.name" %> <span class="required">*</span>
    </label>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <%= f.text_field :name, class: "form-control", required: true,
        placeholder: "Vui lòng nhập tên tour du lịch..." %>
    </div>
  </div>

  <div class="form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">
      <%= t "admin_categories.title" %> <span class="required">*</span>
    </label>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <select class="select2_single form-control" tabindex="-1" id="tour_category_id" name="tour[category_id]">
        <option></option>
        <% @categories.each do |category| %>
          <option value="<%= category.id %>" <%= "selected" if category.id == @tour.category_id %> ><%= category.title %></option>
        <% end %>
      </select>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">
      <%= t "admin_bookings.discount" %> <span class="required">*</span>
    </label>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <select class="select2_single form-control" tabindex="-1" id="tour_discount_id" name="tour[discount_id]">
        <option></option>
        <% @discounts.each do |discount| %>
          <option value="<%= discount.id %>" <%= "selected" if @tour.discount && discount.id == @tour.discount_id %> ><%= discount.name %></option>
        <% end %>
      </select>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">
      <%= t "admin_tours.start_place" %> <span class="required">*</span>
    </label>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <select class="select2_single form-control" tabindex="-1" id="tour_start_place_id" name="tour[start_place_id]">
        <option></option>
        <% @places.each do |place| %>
          <option value="<%= place.id %>" <%= "selected" if place.id == @tour.start_place_id %> ><%= place.name %></option>
        <% end %>
      </select>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">
      <%= t "admin_tours.end_place" %> <span class="required">*</span>
    </label>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <select class="select2_single form-control" tabindex="-1" id="tour_end_place_id" name="tour[end_place_id]">
        <option></option>
        <% @places.each do |place| %>
          <option value="<%= place.id %>" <%= "selected" if place.id == @tour.end_place_id %> ><%= place.name %></option>
        <% end %>
      </select>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">
      <%= t "admin_tours.price" %> <span class="required">*</span>
    </label>
    <div class="col-md-4 col-sm-6 col-xs-12">
      <%= f.text_field :price, class: "form-control", required: true,
        placeholder: "Vui lòng nhập giá tiền..." %>
    </div>
    <div class="col-md-2">
      <select name="tour[currency]", class="form-control">
        <option value="vnd">VNĐ</option>
        <option value="usd">USD</option>
      </select>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">
      <%= t "admin_tours.date" %><span class="required">*</span>
    </label>
    <div class="col-md-3 col-sm-6 col-xs-12">
      <%= f.text_field :start_date, class: "form-control datetimepicker",
        placeholder: "Ngày bắt đầu...",
        value: "#{f.object.start_date.strftime("%d-%m-%Y") if f.object.start_date}" %>
    </div>
    <div class="col-md-3 col-sm-6 col-xs-12">
      <%= f.text_field :end_date, class: "form-control datetimepicker",
        placeholder: "Ngày kết thúc...",
        value: "#{f.object.end_date.strftime("%d-%m-%Y") if f.object.end_date}" %>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">
      <%= t "admin_tours.num" %> <span class="required">*</span>
    </label>
    <div class="col-md-3 col-sm-6 col-xs-12">
      <%= f.text_field :min_visitors, class: "form-control",
        required: true, placeholder: "SL tối thiểu" %>
    </div>
    <div class="col-md-3 col-sm-6 col-xs-12">
      <%= f.text_field :max_visitors, class: "form-control",
        required: true, placeholder: "SL tối đa" %>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">
      <%= t "admin_tours.accommodation" %> <span class="required">*</span>
    </label>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <%= f.text_area :accommodation, class: "form-control", required: true,
        placeholder: "Vui lòng nhập thông tin chỗ ở..." %>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">
      <%= t "admin_tours.meals" %> <span class="required">*</span>
    </label>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <%= f.text_area :meals, class: "form-control", required: true,
        placeholder: "Vui lòng nhập thông tin bữa ăn..." %>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">
      <%= t "admin_tours.transport" %> <span class="required">*</span>
    </label>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <%= f.text_area :transport, class: "form-control", required: true,
        placeholder: "Vui lòng nhập thông tin phương tiện đi lại..." %>
    </div>
  </div><div class="form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">
      <%= t "admin_tours.service" %> <span class="required">*</span>
    </label>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <%= f.text_area :additional_services, class: "form-control",
        required: true, placeholder: "Vui lòng nhập thông tin dịch vụ đi kèm..." %>
    </div>
  </div>
  <div class="ln_solid"></div>
  <div class="form-group">
    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
      <%= f.submit t("save"), class: "btn btn-success" %>
    <%= link_to t("cancel"), admin_tours_path, class: "btn btn-primary" %>
    </div>
  </div>
<% end %>
<!-- Select2 -->
  <script>
    $(document).ready(function() {
      $(".select2_single").select2({
        placeholder: "Please select ...",
        allowClear: true
      });
      $(".select2_group").select2({});
      $(".select2_multiple").select2({
        maximumSelectionLength: 4,
        placeholder: "With Max Selection limit 4",
        allowClear: true
      });
    });
  </script>
<!-- /Select2 -->

app/views/admin/tours/index.html.erb
<% provide :title, t("admin_tours.title") %>
<div class="">
  <div class="page-title">
    <div class="title_left">
      <h3><% t "admin_tours.title" %></h3>
    </div>
  </div>
  <div class="clearfix"></div>

  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2><%= t "admin_tours.all" %>
            <%= link_to t("admin_manage.create"), new_admin_tour_path,
            class: "btn btn-success btn-xs glyphicon glyphicon-plus" %></h2>
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <table id="categories-table" class="table table-striped table-bordered">
            <thead>
              <tr>
                <th><%= t "admin_tours.id" %></th>
                <th><%= t "admin_tours.name" %></th>
                <th><%= t "admin_tours.place" %></th>
                <th><%= t "admin_tours.date" %></th>
                <th><%= t "admin_tours.price" %></th>
                <th><%= t "admin_tours.num" %></th>
                <th><%= t "admin_manage.action" %></th>
            </thead>
            <tbody>
              <% @tours.each do |tour| %>
                <tr>
                  <td><%= tour.id %></td>
                  <td><%= link_to tour.name, admin_tour_path(tour) %></td>
                  <td><%= tour.start_place.name %> - <%= tour.end_place.name %></td>
                  <td><%= tour.start_date.strftime("%d/%m/%Y") %> - <%= tour.end_date.strftime("%d/%m/%Y") %></td>
                  <td>
                    <% if tour.vnd? %>
                      <%= tour.price.round %> <%= t "vnd" %>
                    <% else %>
                      <%= t "usd" %><%= tour.price.round(2) %>
                    <% end %>
                  </td>
                  <td><%= tour.min_visitors %> - <%= tour.max_visitors %></td>
                  <td>
                    <%= link_to edit_admin_tour_path(tour), class: "btn btn-round btn-info btn-xs" do %>
                      <i class="fa fa-pencil-square-o "></i><%= t "admin_manage.edit" %>
                    <% end %>
                    <%= link_to [:admin, tour], method: :delete, class: "btn btn-round btn-danger btn-xs" do %>
                      <i class="fa fa-times"></i><%= t "admin_manage.delete" %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function () {
    //DataTable
    $('#categories-table').DataTable();
  })
</script>

app/views/admin/tours/new.html.erb
<% provide :title, t("admin_tours.title") %>
<div class="">
  <div class="page-title">
    <div class="title_left">
      <h3><% t "admin_tours.title" %></h3>
    </div>
  </div>
  <div class="clearfix"></div>
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2><%= t "admin_tours.new" %></h2>
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <br />
          <%= render "tour_form" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/tours/show.html.erb
<% provide :title, @tour.name %>
<div class="row" style="margin-left:50px;">
  <h2><strong><%= t "admin_tours.detail" %></strong></h2>
  <div>
    <label><%= t "admin_tours.name" %>: </label>
    <%= @tour.name %>
  </div>
  <div>
    <label><%= t "admin_tours.start_place" %>: </label>
    <%= @tour.start_place.name %>
  </div>
  <div>
    <label><%= t "admin_tours.end_place" %>: </label>
    <%= @tour.end_place.name %>
  </div>
  <div>
    <label><%= t "admin_tours.price" %>: </label>
    <% if @tour.vnd? %>
      <%= @tour.price.round %> <%= t "vnd" %>
    <% else %>
      <%= t "usd" %><%= @tour.price %>
    <% end %>
  </div>
  <div>
    <label><%= t "admin_tours.start_date" %>: </label>
    <%= @tour.start_date.strftime("%d-%m-%Y") %>
  </div>
  <div>
    <label><%= t "admin_tours.end_date" %>: </label>
    <%= @tour.end_date.strftime("%d-%m-%Y") %>
  </div>
  <div>
    <label><%= t "admin_tours.min" %>: </label>
    <%= @tour.min_visitors %>
  </div>
  <div>
    <label><%= t "admin_tours.max" %>: </label>
    <%= @tour.max_visitors %>
  </div>
  <div>
    <label><%= t "admin_categories.title" %>: </label>
    <%= @tour.category.title %>
  </div>
  <% if @tour.discount %>
    <label><%= t "admin_bookings.discount" %>: </label>
    <%= @tour.discount.name %> - <%= @tour.discount.percent %>%
  <% end %>
  <div>
    <label><%= t "admin_tours.accommodation" %>: </label>
    <%= @tour.accommodation %>
  </div>
  <div>
    <label><%= t "admin_tours.meals" %>: </label>
    <%= @tour.meals %>
  </div>
  <div>
    <label><%= t "admin_tours.transport" %>: </label>
    <%= @tour.transport %>
  </div>
  <div>
    <label><%= t "admin_tours.service" %>: </label>
    <%= @tour.additional_services %>
  </div>
  <div>
    <%= link_to t("edit"), edit_admin_tour_path(@tour),
      class: "btn btn-primary" %>
    <%= link_to t("delete"), [:admin, @tour], method: :delete,
      data: {confirm: t("sure")}, class: "btn btn-danger" %>
  </div>
</div>