config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"

  devise_for :users, :controllers => {:sessions => "my_devise/sessions"}
  root "static_pages#home"
  get "/static_pages/:page" => "static_pages#show", as: "static_pages"
  resources :places do
    collection {post :search, to: "places#index"}
    resources :reviews, except: :index
  end
  resources :tours do
    collection {post :search, to: "tours#index"}
    resources :bookings, except: [:edit, :update, :index]
  end
  resources :bookings, except: [:edit, :destroy] do
    resources :payments, only: [:new, :create, :update]
  end
  resources :reviews do
    resources :comments
  end
  resources :comments do
    resources :comments
  end
  resources :users
  resources :discounts, only: [:show, :index]
  resources :categories, only: :show
  resources :payments, only: [:show, :index]

  namespace :admin do
    root "static_pages#home", as: "static_pages"
    get "static_pages/:page" => "static_pages#show"
    resources :categories, except: [:show]
    resources :tours do
      collection {post :search, to: "tours#index"}
    end
    resources :bookings, except: [:new, :create] do
      collection {post :search, to: "bookings#index"}
    end
    resources :places, except: [:show] do
      collection {post :search, to: "places#index"}
      resources :reviews, only: [:show, :destroy]
    end
    resources :reviews, only: [:show, :index, :destroy] do
      resources :comments, only: [:show, :destroy]
    end
    resources :users do
      collection {post :search, to: "users#index"}
    end
    resources :discounts do
      collection {post :search, to: "discounts#index"}
    end
    resources :payments,  only: [:show, :index]
    resources :notifications, only: :index
  end
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
  load_and_authorize_resource

  def index
  end

  def show
    @comments = @review.comments
  end

  def destroy
    @place = @review.place
    if @review.delete
      flash[:notice] = t "admin_reviews.delete_success"
    else
      flash[:alert] = t "admin_reviews.delete_fail"
    end
    redirect_to :back
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  load_and_authorize_resource params_method: :review_params

  def show
    @comment = Comment.new
    @comments = @review.comments
  end

  def new
    @place = Place.find_by_id params[:place_id]
    @review = Review.new
  end

  def create
    @review = current_user.reviews.build review_params
    if @review.save
      Notification.create user: current_user, notifiable_type: "Review", notifiable_id: @review.id
      flash[:notice] = t "user_reviews.create_success"
      redirect_to place_path @review.place
    else
      flash[:alert] = t "user_reviews.create_fail"
      @place = Place.find_by_id params[:place_id]
      render :new
    end
  end

  def edit
    @place = Place.find_by_id params[:place_id]
  end

  def update
    if @review.update_attributes review_params
      flash[:notice] = t "user_reviews.update_success"
      redirect_to place_path @review.place
    else
      flash[:alert] = t "user_reviews.update_fail"
      render :edit
    end
  end

  def destroy
    @place = @review.place
    if @review.delete
      flash[:notice] = t "user_reviews.delete_success"
    else
      flash[:alert] = t "user_reviews.delete_fail"
    end
    redirect_to place_path @place
  end

  private
  def review_params
    params.require(:review).permit :title, :content, :place_id
  end
end

app/views/admin/reviews/_index.html.erb
<% @reviews.each do |review| %>
  <div>
    <%= link_to review.title, admin_place_review_path(review.place, review) %>
    <br />
    <span class="usertimestamp">
      Posted by <%= review.user.username %>
        <%= time_ago_in_words(review.created_at) %> ago.
    </span>
    <span class="content">
      <%= review.content.html_safe %>
    </span>
    <br />
    <span>
      <%= link_to t("delete"), [:admin, review.place, review], method: :delete,
        data: {confirm: t("sure")}, class: "btn btn-danger" %>
    </span>
  </div>
<% end %>

app/views/admin/reviews/index.html.erb
<% provide :title, t("admin_reviews.base_title") %>
<div class="">
  <div class="page-title">
    <div class="title_left">
      <h3><%= t "admin_reviews.base_title" %></h3>
    </div>
  </div>
  <div class="clearfix"></div>

  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2><%= t "admin_reviews.all" %></h2>
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <table id="users-table" class="table table-striped table-bordered">
            <thead>
              <tr>
                <th><%= t "admin_reviews.id" %></th>
                <th><%= t "admin_reviews.name" %></th>
                <th><%= t "admin_reviews.place" %></th>
                <th><%= t "admin_reviews.author" %></th>
                <th><%= t "admin_manage.action" %></th>
            </thead>
            <tbody>
              <% @reviews.each do |review| %>
                <tr>
                  <td><%= review.id %></td>
                  <td><%= link_to review.title, admin_review_path(review) %></td>
                  <td><%= link_to review.place.name, admin_place_path(review.place) %></td>
                  <td><%= review.user.username %></td>
                  <td>
                    <%= link_to [:admin, review], method: :delete, class: "btn btn-round btn-danger btn-xs" do %>
                      <i class="fa fa-user-circle-o"></i>  <%= t "admin_manage.delete" %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function () {
    //DataTable
    $('#users-table').DataTable();
  })
</script>

app/views/admin/reviews/show.html.erb
<div style="margin-left:50px; font-size:20px;">
  <h4><strong><%= @review.title %></strong></h4>
  <span class="content">
    <%= @review.content.html_safe %>
  </span>
  <span class="usertimestamp" style="font-size:12px;">
    Posted by <%= @review.user.username %>
      <%= time_ago_in_words(@review.created_at) %> ago.
  </span>
  <br />
  <span>
    <%= link_to t("delete"), [:admin, @review.place, @review], method: :delete,
      data: {confirm: t("sure")}, class: "btn btn-danger" %>
  </span>
</div>
<%= render "admin/comments/index", review: @review %>