config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"

  devise_for :users, :controllers => {:sessions => "my_devise/sessions"}
  root "static_pages#home"
  get "/static_pages/:page" => "static_pages#show", as: "static_pages"
  resources :places do
    collection {post :search, to: "places#index"}
    resources :reviews, except: :index
  end
  resources :tours do
    collection {post :search, to: "tours#index"}
    resources :bookings, except: [:edit, :update, :index]
  end
  resources :bookings, except: [:edit, :destroy] do
    resources :payments, only: [:new, :create, :update]
  end
  resources :reviews do
    resources :comments
  end
  resources :comments do
    resources :comments
  end
  resources :users
  resources :discounts, only: [:show, :index]
  resources :categories, only: :show
  resources :payments, only: [:show, :index]

  namespace :admin do
    root "static_pages#home", as: "static_pages"
    get "static_pages/:page" => "static_pages#show"
    resources :categories, except: [:show]
    resources :tours do
      collection {post :search, to: "tours#index"}
    end
    resources :bookings, except: [:new, :create] do
      collection {post :search, to: "bookings#index"}
    end
    resources :places, except: [:show] do
      collection {post :search, to: "places#index"}
      resources :reviews, only: [:show, :destroy]
    end
    resources :reviews, only: [:show, :index, :destroy] do
      resources :comments, only: [:show, :destroy]
    end
    resources :users do
      collection {post :search, to: "users#index"}
    end
    resources :discounts do
      collection {post :search, to: "discounts#index"}
    end
    resources :payments,  only: [:show, :index]
    resources :notifications, only: :index
  end
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates_presence_of :name, :description
  validates_uniqueness_of :name
end

app/controllers/admin/places_controller.rb
class Admin::PlacesController < ApplicationController
  load_and_authorize_resource params_method: :place_params

  def index
    @search = Place.search params[:q]
    @places = @search.result
  end

  def new
    @place = Place.new
  end

  def create
    if @place.save
      flash[:notice] = t "admin_places.create_success"
      redirect_to admin_places_path
    else
      flash[:alert] = t "admin_places.create_fail"
      render :new
    end
  end

  def edit
  end

  def update
    if @place.update_attributes place_params
      flash[:notice] = t "admin_places.update_success"
      redirect_to admin_places_path
    else
      flash[:alert] = t "admin_places.update_fail"
      render :edit
    end
  end

  def destroy
    if @place.destroy
      flash[:notice] = t "admin_places.delete_success"
      redirect_to admin_places_path
    else
      flash[:alert] = t "admin_places.delete_fail"
      redirect_to admin_places_path
    end
  end

  private
  def place_params
    params.require(:place).permit :name, :description
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  load_and_authorize_resource

  def index
    @search = Place.search params[:q]
    @places = @search.result
  end

  def show
    @reviews = @place.reviews
  end
end

app/views/admin/places/edit.html.erb
<% provide :title, t("admin_places.title") %>
<div class="">
  <div class="page-title">
    <div class="title_left">
      <h3><%= t "admin_places.title" %></h3>
    </div>
  </div>
  <div class="clearfix"></div>
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2><%= t "admin_places.edit" %></h2>
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <br />
          <%= form_for [:admin, @place], html: {class: "form-horizontal form-label-left"} do |f| %>
            <div class="form-group">
              <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                <%= render "shared/error_messages", object: @place %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">
                <%= t "admin_places.name" %><span class="required">*</span>
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <%= f.text_field :name, class: "form-control col-md-7 col-xs-12", required: true,
                  placeholder: "Nhập tên điểm du lịch ..." %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">
                <%= t "admin_places.description" %><span class="required">*</span>
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <%= f.text_area :description, class: "form-control", required: true,
                  placeholder: "Nhập mô tả điểm du lịch ..."%>
              </div>
            </div>

            <div class="ln_solid"></div>
            <div class="form-group">
              <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                <%= f.submit t("save"), class: "btn btn-success" %>
                <%= link_to t("cancel"), admin_places_path, class: "btn btn-primary" %>
              </div>
            </div>

          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/places/index.html.erb
<% provide :title, t("admin_places.title") %>
<div class="">
  <div class="page-title">
    <div class="title_left">
      <h3><%= t "admin_places.title" %></h3>
    </div>
  </div>
  <div class="clearfix"></div>

  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2><%= t "admin_places.all" %><%= link_to t("admin_manage.create"), new_admin_place_path,
            class: "btn btn-success btn-xs glyphicon glyphicon-plus" %></h2>
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <table id="places-table" class="table table-striped table-bordered">
            <thead>
              <tr>
                <th><%= t "admin_places.id" %></th>
                <th><%= t "admin_places.name" %></th>
                <th><%= t "admin_places.description" %></th>
                <th><%= t "admin_manage.action" %></th>
            </thead>
            <tbody>
              <% @places.each do |place| %>
                <tr>
                  <td><%= place.id %></td>
                  <td><%= place.name %></td>
                  <td style="width:60%"><%= place.description %></td>
                  <td>
                    <%= link_to edit_admin_place_path(place), class: "btn btn-round btn-info btn-xs" do %>
                      <i class="fa fa-pencil-square-o "></i><%= t "admin_manage.edit" %>
                    <% end %>
                    <%= link_to [:admin, place], method: :delete, data: {confirm: t("sure")}, class: "btn btn-round btn-danger btn-xs" do %>
                      <i class="fa fa-times"></i><%= t "admin_manage.delete" %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function () {
    //DataTable
    $('#places-table').DataTable();
  })
</script>

app/views/admin/places/new.html.erb
<% provide :title, t("admin_places.title") %>
<div class="">
  <div class="page-title">
    <div class="title_left">
      <h3><%= t "admin_places.title" %></h3>
    </div>
  </div>
  <div class="clearfix"></div>
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2><%= t "admin_places.new" %></h2>
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <br />
          <%= form_for [:admin, @place], html: {class: "form-horizontal form-label-left"} do |f| %>
            <div class="form-group">
              <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                <%= render "shared/error_messages", object: @place %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">
                <%= t "admin_places.name" %><span class="required">*</span>
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <%= f.text_field :name, class: "form-control col-md-7 col-xs-12", required: true,
                  placeholder: "Nhập tên điểm du lịch ..." %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">
                <%= t "admin_places.description" %><span class="required">*</span>
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <%= f.text_area :description, class: "form-control", required: true,
                  placeholder: "Nhập mô tả điểm du lịch ..."%>
              </div>
            </div>

            <div class="ln_solid"></div>
            <div class="form-group">
              <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                <%= f.submit t("save"), class: "btn btn-success" %>
                <%= link_to t("cancel"), admin_places_path, class: "btn btn-primary" %>
              </div>
            </div>

          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>